# Set OS to linux
os: linux
dist: bionic

# Set the build language to Python
language: python

# Set the python version to 3.5
python: 3.6

before_install:
  - sudo apt-get update

# Install the library dependencies
install:
  - sudo apt-get install python3
  - pip install numpy opencv-python

# Run python scripts
script:
  - python main.py
